# Generated by Django 3.2.5 on 2021-10-11 00:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('37216a4d-60c2-451d-8694-4eea032f5ad0'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f9e3cb9f-fc18-49c7-8cbb-2fd1ec1b1ed3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc80bba8-8110-4c9b-a32a-e56d8c70b1ee'), primary_key=True, serialize=False),
        ),
    ]
