# Generated by Django 3.2.5 on 2021-10-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20211011_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='option1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='option2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='option3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
