# Generated by Django 3.2.5 on 2021-10-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20211011_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='option4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
