# Generated by Django 3.2.5 on 2021-10-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_post_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='post.Comment'),
        ),
    ]
