# Generated by Django 3.2.5 on 2021-10-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='session_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
