# Generated by Django 3.2.5 on 2021-10-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_comment_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='session_key',
            new_name='user_key',
        ),
    ]
