# Generated by Django 3.2.5 on 2021-10-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_rename_session_key_comment_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
