# Generated by Django 3.2.5 on 2021-10-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_useraccount_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(default='Admin', max_length=255),
            preserve_default=False,
        ),
    ]
