# Generated by Django 3.2.5 on 2021-10-12 03:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wanted',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('crime', models.CharField(max_length=255)),
                ('reward', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='images/')),
            ],
        ),
    ]
