# Generated by Django 3.2.5 on 2021-10-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wanted',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='wanted',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-12-12 12:12:30'),
            preserve_default=False,
        ),
    ]
