# Generated by Django 3.2.5 on 2021-10-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_post_comments'),
        ('wanted', '0002_auto_20211011_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanted',
            name='comments',
            field=models.ManyToManyField(blank=True, to='post.Comment'),
        ),
    ]
