# Generated by Django 3.2.5 on 2021-10-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0003_wanted_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanted',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
